server:
  port: 8888

azure:
  speech:
    key: 7Cf0s1wxJKfV4zmnwPEk3F7VT1N34CUgS6gXXxBVZclVEEOVw2GmJQQJ99BGACYeBjFXJ3w3AAAYACOGJL4K
    region: eastus
    language: en-US
    endpoint-template: https://eastus.stt.speech.microsoft.com/speech/recognition/conversation/cognitiveservices/v1
    content-type: audio/wav
    accept: application/json
    user-agent: SpringBoot-STT-Service
